export default [
  { "_id": "A101", "title": "Propulsion Assignment", "course": "RS101" },
  { "_id": "A102", "title": "Combustion Analysis", "course": "RS101" },
  { "_id": "A103", "title": "Nozzle Design Project", "course": "RS101" },
  { "_id": "A201", "title": "Aerodynamics Quiz", "course": "RS102" },
  { "_id": "A202", "title": "Flow Analysis", "course": "RS102" },
  { "_id": "A203", "title": "Heating Analysis", "course": "RS102" },
  { "_id": "A301", "title": "Structural Design Task", "course": "RS103" },
  { "_id": "A302", "title": "Orbital Calculations", "course": "RS103" },
  { "_id": "A303", "title": "Systems Engineering Exam", "course": "RS103" },
  { "_id": "A401", "title": "Satellite Communication", "course": "RS104" },
  { "_id": "A402", "title": "Radar Systems Lab", "course": "RS104" },
  { "_id": "A403", "title": "Signal Processing Quiz", "course": "RS104" },
  { "_id": "A501", "title": "Flight Dynamics Assignment", "course": "RS105" },
  { "_id": "A502", "title": "Control Systems Design", "course": "RS105" },
  { "_id": "A503", "title": "Navigation System Project", "course": "RS105" },
  { "_id": "A601", "title": "Rocket Propellants Research", "course": "RS106" },
  { "_id": "A602", "title": "Thermodynamics Exam", "course": "RS106" },
  { "_id": "A603", "title": "Pressure Vessel Design", "course": "RS106" },
  { "_id": "A701", "title": "Mechanical Vibrations Quiz", "course": "RS107" },
  { "_id": "A702", "title": "Advanced Robotics Lab", "course": "RS107" },
  { "_id": "A703", "title": "Control Theory Assignment", "course": "RS107" },
  { "_id": "A801", "title": "Fluid Dynamics Final Project", "course": "RS108" },
  { "_id": "A802", "title": "Energy Systems Analysis", "course": "RS108" },
  { "_id": "A803", "title": "Material Science Exam", "course": "RS108" }
]
